mvratings/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :ratings
  root 'movies#index'

  resources :movies do
    resources :ratings, shallow: true
  end

  get 'query',to:'movies#index'
  get 'static_show', to: 'movies#viewMovie'
  get 'sort', to: 'movies#index' # this is wrong

end

mvratings/app/models/movie.rb
class Movie < ActiveRecord::Base
end

mvratings/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :User
end

mvratings/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

mvratings/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :authenticate_user!
  @time = Time.now
end

mvratings/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    #@movies = Movie.all
    @query = nil
    @gValues = Tmdb::Genre.movie_list
    @input = params[:user_input]
    @time = Time.now
    if(params[:user_input] != "" && @input != nil) 
      @query = Tmdb::Search.movie(@input).results
    elsif (params[:sort] == "1")
      @input = params[:q]
      @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['title']}
      if (params[:pivot] == "tf")
         @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['title']}.reverse!
         @lpivot = "tb"
      else
         @lpivot = "tf"
      end
    elsif (params[:sort] == "2")
      @input = params[:q]
      @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['release_date']}
      if (params[:pivot] == "tf2")
         @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['release_date']}.reverse!
         @lpivot = "tb2"
      else
         @lpivot = "tf2"
      end
    elsif (params[:sort] == "3")
      @input = params[:q]
      @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['genre_ids']}
      if (params[:pivot] == "tf3")
         @query = Tmdb::Search.movie(@input).results.sort_by{|h| h['genre_ids']}.reverse!
         @lpivot = "tb3"
      else
         @lpivot = "tf3"
      end
    end

  end

  def viewMovie   #pratically a show
    @title = params[:title]
    @overview = params[:overview]
    @id = params[:id]
    @rdb = Rating.all
    @rating = Rating.new
    @user = User.all
  end
  def sort
    @query = params[:q]
    @gValues = Tmdb::Genre.movie_list
    
  end
  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      #@movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.fetch(:movie,:mv, {})
    end
end

mvratings/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end
  
  # def setRating

  # end
  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:movieId, :stars, :date, :User_id)
    end
end

mvratings/app/helpers/application_helper.rb
module ApplicationHelper
end

mvratings/app/helpers/movies_helper.rb
module MoviesHelper
end

mvratings/app/helpers/ratings_helper.rb
module RatingsHelper
end

mvratings/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mvratings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<div id="user_nav">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or
<%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>
<div>
  <%= form_tag(query_path, method: "get") do %>
    <%= label_tag(:user_input, "Search for a movie")%>
    <%= text_field_tag(:user_input) %>
    <%= hidden_field_tag(:time, @time) %>
    <%= submit_tag("Search") %>
  <% end %>

</div>
<%= yield %>
<%= link_to 'Home', movies_path %>
<%= link_to 'All Reviews', ratings_path %>
</body>
</html>

mvratings/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mvratings/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

mvratings/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <h2> Welcome to the movie rating site </h2>
  <tbody>

    <% if (@query != nil) %>
      <tr>
        <td><strong><%= link_to "Title", sort_path(:sort => "1", :q => @input, :pivot => @lpivot) %></strong></td>
        <td><strong><%= link_to "Release", sort_path(:sort => "2", :q => @input, :piovt => @lpivot) %></strong></td>
        <td><strong><%= link_to "Genre", sort_path(:sort => "3", :q => @input, :pivot => @lpivot) %></strong></td>
      </tr>
    
      <% @query.each do |movie| %>
        <tr>
          <td><%= link_to movie.title, static_show_path(:title => movie.title,
                                                    :overview => movie.overview,
                                                    :id => movie.id) %> </td>
          <td><%= movie.release_date%></td>
          <td>
            <% movie.genre_ids.each do |id| %>
              <%= @gValues.find {|h1| h1['id']== id }['name'] %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>

</table>

<br>

mvratings/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

mvratings/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>hello</p>

mvratings/app/views/movies/sort.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>
<%= @test %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <br>
  <tbody>
</script>
    <% if (@query != nil) %>
      <tr>
        <td><strong><%= link_to "Title", sort_path(:q => @query) %></strong></td>
        <td><strong>Release</strong></td>
        <td><strong>Genre</strong></td>
      </tr>
    
      <% @query.results.each do |movie| %>
        <tr>
          <td><%= link_to movie.title, static_show_path(:title => movie.title,
                                                    :overview => movie.overview,
                                                    :id => movie.id) %> </td>
          <td><%= movie.release_date%></td>
          <td>
            <% movie.genre_ids.each do |id| %>
              <%= @gValues.find {|h1| h1['id']== id }['name'] %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>

</table>

<br>

mvratings/app/views/movies/viewMovie.html.erb
<br>
<%= @title %>
<br><br>
<%= @overview %>
<br><br><br>

<% @rdb.each do |r| %>
	<% if (r.movieId == @id) %>
		<%= r.stars %>
	<% end %>
<% end %>

<% if user_signed_in? %>
	<%= render 'ratings/form' %>
	<br><br>
<% end %>

<table><tbody>
	<tr>
		<td>Rating</td>
		<td>Created at</td>
		<td>Created By</td>
	</tr>
	<% @rdb.each do |r| %>
		<tr>
			<% if (r.movieId.to_i == @id.to_i) %>
				<td><%= r.stars %></td>
				<td><%= r.created_at %></td>
				<td><%= @user.at(r.User_id-1).email %></td>
			<% end %>
		</tr>
	<% end %>
</tbody></table>

mvratings/app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :movieId, :value => @id %>
  </div>
  <div class="field">
    <%= f.label :stars %> (0-5) <br>
    <%= f.number_field :stars, max: 5 %>
  </div>
  <div class="field">
    <%= f.hidden_field :User_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mvratings/app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

mvratings/app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Stars</th>
      <th>Date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= Tmdb::Movie.detail(rating.movieId).title %></td>
        <td><%= rating.stars %></td>
        <td><%= rating.created_at %></td>
        <td><%= rating.User.email %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

mvratings/app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

mvratings/app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movieid:</strong>
  <%= @rating.movieId %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @rating.stars %>
</p>

<p>
  <strong>Date:</strong>
  <%= @rating.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.User %>
</p>

<%= link_to 'Back', ratings_path %>